import Head from 'next/head';
import Banner from '../components/molecules/Banner';
import Footer from '../components/organisms/Footer';
import Header from '../components/organisms/Header';
import LargeCard from '../components/molecules/LargeCard';
import MediumCardsSection from '../components/organisms/MediumCardsSection';
import SmallCardsSection from '../components/organisms/SmallCardsSection';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div >
      <Head>
        <title>LeoBnB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/download.png" />
      </Head>

      <Header />
      <br />
      <hr />
      <Banner />
      <SmallCardsSection />
      <br />
      <hr />
      <MediumCardsSection />
      <br />
      <hr />
      <LargeCard img="https://links.papareact.com/4cj" buttonText="Get Inspired" description="Wishlists curated by Airbnb" title="The Greatest Outdoors"/>
      <Footer />
    </div>
  )
}
